evaluator_name: "tooleval_gemini"
registered_cls_name: "ReinforceToolLearningEvaluator"
prompt_template: "template.txt"
fn_completions: "normalized_gemini_completions"
api_key: your-api-key
completions_kwargs:
  model: "gemini-2.5-flash"
  max_tokens: 1000
  temperature: 0.2
  timeout: 10
  functions:
    - name: "check_answer_status"
      description: "Parse the json answer with layerd nodes and return the answer_status about the answer"
      parameters:
        type: "object"
        properties:
          answer_status:
            type: "string"
            enum: ["Unsure","Unsolved","Solved"]
        required: ["answer_status"]
    - name: "parse_answer_status"
      description: "Parse the json answer with layerd nodes and return the answer_status about the answer"
      parameters:
        type: "object"
        properties:
          answer_status:
            type: "string"
            enum: ["Unsure","Unsolved","Solved"]
        required: ["answer_status"]
    - name: "check_task_solvable"
      description: "Parse the task description and return the task_status about the task"
      parameters:
        type: "object"
        properties:
          task_status:
            type: "string"
            enum: ["Unsure","Unsolvable","Solvable"]
        required: ["task_status"]
    - name: "select_better_answer"
      description: "Select the better answer with a comprehensive investigation on given aspects. You should ignore the impact of the order of candidate answers."
      parameters:
        type: "object"
        properties:
          index:
            type: "number"
            description: "The `index` value in the selected better answer."
        required: ["index"]
fn_completion_parser: "index_parser"
batch_size: 1