gemini_key: "AIzaSyC-mYLThr_c-1pHmgSswfbtmUq0mtC_HYE"
gemini_base: "https://generativelanguage.googleapis.com"
gemini_model: gemini-2.5-flash
temperature: 0
toolbench_url: http://8.130.32.149:8080/rapidapi
tools_folder: "../tools"
cache_folder: "./tool_response_cache"
is_save: true
port: 8080
log_file: "./server.log"